openapi: 3.0.3
info:
  title: OpenAPI schema for template terraform-kubernetes-rabbitmq
components:
  schemas:
    variables:
      required: []
      type: object
      properties:
        context:
          title: Context
          type: object
          description: |
            Receive contextual information. When Walrus deploys, Walrus will inject specific contextual information into this field.
          default: {}
          additionalProperties:
            type: object
            x-walrus-ui:
              colSpan: 12
          x-walrus-ui:
            colSpan: 12
            group: Advanced
            hidden: true
            order: 1
        infrastructure:
          title: Infrastructure
          type: object
          description: |
            Specify the infrastructure information for deploying.
          default: {}
          properties:
            domain_suffix:
              description: |
                Specify the domain name of the Kubernetes cluster.
              default: cluster.local
              title: Domain Suffix
              type: string
              x-walrus-ui:
                order: 3
            image_registry:
              description: |
                Specify the image registry to pull the bitnami/rabittmq image, default is `registry-1.docker.io`.
              default: registry-1.docker.io
              title: Image Registry
              type: string
              x-walrus-ui:
                order: 2
            namespace:
              title: Namespace
              type: string
              x-walrus-ui:
                hidden: true
                order: 1
          x-walrus-ui:
            colSpan: 12
            group: Advanced
            order: 2
        engine_version:
          title: Engine Version
          type: string
          description: |
            Specify the deployment engine version, select from https://hub.docker.com/r/bitnami/rabbitmq/tags.
          default: "3.11"
          x-walrus-ui:
            group: Basic
            order: 3
        username:
          title: Username
          type: string
          description: |
            Specify the account username. The username must be 2-16 characters long and start with lower letter, combined with number, or symbol: _.
          default: user
          minLength: 2
          maxLength: 16
          x-walrus-ui:
            group: Basic
            order: 4
        password:
          title: Password
          type: string
          description: |
            Specify the account password. The password must be 8-32 characters long and start with any letter, number, or symbols: ! # $ % ^ & * ( ) _ + - =.
            If not specified, it will generate a random password.
          format: password
          writeOnly: true
          minLength: 8
          maxLength: 32
          x-walrus-ui:
            group: Basic
            order: 5
        resources:
          title: Resources
          type: object
          description: |
            Specify the computing resources.
          default:
            cpu: 0.25
            memory: 256
          properties:
            cpu:
              description: |
                Specify the cpu resources. Unit is core.
              default: 0.25
              title: Cpu(Core)
              type: number
              x-walrus-ui:
                order: 1
            memory:
              description: |
                Specify the memory resources. Unit is megabyte.
              default: 256
              title: Memory(MiB)
              type: number
              x-walrus-ui:
                order: 2
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 6
        storage:
          title: Storage
          type: object
          description: |
            Specify the storage resources.
          properties:
            class:
              description: |
                Specify the storage class. If not specified, it will use the default provisioner.
              title: Class
              type: string
              x-walrus-ui:
                order: 1
            size:
              description: |
                Specify the storage size. Unit is megabyte.
              default: 20480
              title: Size(MiB)
              type: number
              x-walrus-ui:
                order: 2
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 7
      x-walrus-ui:
        groupOrder:
        - Basic
        - Advanced
