openapi: 3.0.3
info:
  title: OpenAPI schema for template terraform-kubernetes-rabbitmq
components:
  schemas:
    variables:
      type: object
      properties:
        infrastructure:
          title: Infrastructure
          type: object
          description: |
            Specify the infrastructure information for deploying.
          default: {}
          nullable: true
          properties:
            domain_suffix:
              default: cluster.local
              description: |
                Specify the domain name of the Kubernetes cluster.
              nullable: true
              title: Domain Suffix
              type: string
              x-walrus-ui:
                order: 3
            image_registry:
              default: registry-1.docker.io
              description: |
                Specify the image registry to pull the bitnami/rabittmq image, default is `registry-1.docker.io`.
              nullable: true
              title: Image Registry
              type: string
              x-walrus-ui:
                order: 2
            namespace:
              nullable: true
              title: Namespace
              type: string
              x-walrus-ui:
                hidden: true
                order: 1
            service_type:
              default: NodePort
              description: |
                Specify the service type of the Kubernetes cluster, default is `NodePort`.
              enum:
              - NodePort
              - LoadBalancer
              - ClusterIP
              nullable: true
              title: Service Type
              type: string
              x-walrus-ui:
                order: 4
          x-walrus-ui:
            colSpan: 12
            group: Advanced
            order: 2
        engine_version:
          title: Engine Version
          type: string
          description: |
            Specify the deployment engine version, select from https://hub.docker.com/r/bitnami/rabbitmq/tags.
          default: "3.11"
          nullable: true
          x-walrus-ui:
            group: Basic
            order: 3
        username:
          title: Username
          type: string
          description: |
            Specify the account username. The username must be 2-16 characters long and start with lower letter, combined with number, or symbol: _.
          default: user
          nullable: true
          minLength: 2
          maxLength: 16
          x-walrus-ui:
            group: Basic
            order: 4
        password:
          title: Password
          type: string
          description: |
            Specify the account password. The password must be 8-32 characters long and start with any letter, number, or symbols: ! # $ % ^ & * ( ) _ + - =.
            If not specified, it will generate a random password.
          format: password
          nullable: true
          writeOnly: true
          minLength: 8
          maxLength: 32
          x-walrus-ui:
            group: Basic
            order: 5
        resources:
          title: Resources
          type: object
          description: |
            Specify the computing resources.
          default:
            cpu: 0.25
            memory: 1024
          nullable: true
          properties:
            cpu:
              default: 0.25
              description: |
                Specify the cpu resources. Unit is core.
              minimum: 0.1
              nullable: true
              title: Cpu(Core)
              type: number
              x-walrus-ui:
                order: 1
            memory:
              default: 1024
              description: |
                Specify the memory resources. Unit is megabyte.
              minimum: 512
              nullable: true
              title: Memory(MiB)
              type: number
              x-walrus-ui:
                order: 2
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 6
        storage:
          title: Storage
          type: object
          description: |
            Specify the storage resources.
          nullable: true
          properties:
            class:
              description: |
                Specify the storage class. If not specified, it will use the default provisioner.
              nullable: true
              title: Class
              type: string
              x-walrus-ui:
                order: 1
            size:
              default: 10240
              description: |
                Specify the storage size. Unit is megabyte.
              minimum: 1024
              nullable: true
              title: Size(MiB)
              type: number
              x-walrus-ui:
                order: 2
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 7
      x-walrus-ui:
        groupOrder:
        - Basic
        - Advanced
